### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by antfu** [antfu/regex-doctor#2]
- [ ] Search / filters
- [ ] Auto-test suite generation (bench)
- [ ] Landing package to select output file
- [ ] Hosted version, with JSON upload
- [ ] Load multiple payload to display comparison
- [ ] Meta information (timestamp, process name, node versions, custom tags)
- [ ] Docs
